### ISSUE TITLE
More information on how to set up accounts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/recurring-tasks#37]
https://github.com/srobo/recurring-tasks/blob/master/kickstart/services/user-accounts/mentors.yaml and https://github.com/srobo/recurring-tasks/blob/master/kickstart/services/user-accounts/team-leaders.yaml should provide more information on how to do this. Probably just instructions for the relevant commands in `userman` are enough.

**Comment by WillB97** [comment]
Since we moved to using discord, we no longer create users for mentors and team leaders
