### ISSUE TITLE
Update Media Consent tasks for current policy

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/recurring-tasks#75]
For SR2023 we have a more relaxed policy based on more recent research. Essentially we're moving away from consent forms and towards clearer advertising of various filming activities.
We can therefore remove the tasks relating to media consent forms (MCFs) and wristbands, but will need to add tasks for the red lanyards for people who wish to opt-out.

**Comment by sedders123** [comment]
We should also make sure having clear signage is covered as well as informing teams ahead of time that photos and videos will be taken at the event

**Comment by PeterJCLaw** [comment]
[comp/reception/hardware](https://github.com/srobo/recurring-tasks/blob/main/comp/reception/hardware.yaml) (e.g: https://github.com/srobo/tasks/issues/994) may also become moot as there's no longer any scanning of tickets on the door.
